"""Assemble a throwaway Godot project to run an addon headlessly (TDD 24.3/24.7).

Laser Tag and Lux are Godot addons: their headless entry points are a runner /
driver script inside the addon, invoked with ``godot --headless --path <project>
-s res://<script> -- <args>``. The scene they operate on lives in a Level Factory
work dir, but Godot can only ``load()`` a ``res://`` path, so we stage a minimal
project that contains the addon(s) and the scene (plus its work-dir siblings) at
``res://``.

This is the seam, not a full resource-closure packer: it copies the scene and
the sibling files in its directory (the glbs / json the tscn references by
relative path in a Level Factory job). A deeper closure across res:// references
reuses the exporting/closure module and is the documented follow-up.
"""
from __future__ import annotations

import re
import shutil
from pathlib import Path


def _project_godot(name: str, addon_plugins: list[str]) -> str:
    enabled = ", ".join(f'"res://addons/{p}/plugin.cfg"' for p in addon_plugins)
    return (
        "; Auto-generated by Level Factory staging — throwaway project.\n"
        "config_version=5\n\n"
        "[application]\n"
        f'config/name="{name}"\n'
        'config/features=PackedStringArray("4.7")\n\n'
        "[editor_plugins]\n"
        f"enabled=PackedStringArray({enabled})\n"
    )


def _class_cache_entries(text: str) -> str:
    """Return the inner entries of a global_script_class_cache.cfg `list=[...]`
    (everything between the outermost brackets), so multiple addon caches can be
    merged into one `list=[ ... ]`. Returns "" if the file has no list."""
    start = text.find("[")
    end = text.rfind("]")
    if start == -1 or end == -1 or end <= start:
        return ""
    return text[start + 1:end].strip()


def stage_godot_project(
    dest: Path, *, addon_dirs: list[Path], scene_src: Path,
    plugins: list[str], scene_res_name: str = "level.tscn",
) -> tuple[Path, str]:
    """Create a project at ``dest`` with the addons + the scene at res://.

    Returns (project_dir, res_scene_path) e.g. (.../staging/x, "res://level.tscn").
    """
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "addons").mkdir(exist_ok=True)
    cache_entries: list[str] = []
    for addon in addon_dirs:
        if addon.exists():
            target = dest / "addons" / addon.name
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(addon, target)
            # A staged throwaway project is never opened in the editor, so it
            # has no global script class cache — and Godot can't resolve a
            # class_name TYPE (e.g. LT_MapEvalHarness, LuxRoot) without it,
            # which makes `-s <runner>.gd` fail with "Could not find type".
            # The addon's own repo already has that cache and every entry points
            # under res://addons/<name>/ (verified), so it's copy-safe: pull its
            # entries in. addon = <repo>/addons/<name>, so repo = addon.parent.parent.
            src_cache = addon.parent.parent / ".godot" / "global_script_class_cache.cfg"
            if src_cache.exists():
                cache_entries.append(_class_cache_entries(src_cache.read_text(encoding="utf-8")))
    if cache_entries:
        merged = ", ".join(e for e in cache_entries if e)
        (dest / ".godot").mkdir(exist_ok=True)
        (dest / ".godot" / "global_script_class_cache.cfg").write_text(
            "list=[" + merged + "]\n", encoding="utf-8")
    # Stage the scene + its work-dir siblings (relative-path deps) at res://.
    if scene_src.exists():
        shutil.copy2(scene_src, dest / scene_res_name)
        for sib in scene_src.parent.iterdir():
            if sib.is_file() and sib != scene_src:
                shutil.copy2(sib, dest / sib.name)
    # Resolve closure: Lot bakes the building glb into site.tscn by ABSOLUTE
    # path (non-portable mode prepends res:// to it -> "res://C:/Users/.../
    # shell.glb", which Godot can't load). Copy each such file into the project
    # and rewrite the reference to a real res:// path. Applied to every staged
    # .tscn so site.tscn's building ref (and any other absolute ref) resolves.
    for tscn in dest.glob("*.tscn"):
        _resolve_absolute_refs(tscn, dest)
    (dest / "project.godot").write_text(
        _project_godot(dest.name, plugins), encoding="utf-8")
    return dest, f"res://{scene_res_name}"


_ABS_REF = re.compile(r'path="res://((?:[A-Za-z]:[\\/]|/)[^"]+)"')


def _resolve_absolute_refs(tscn: Path, dest: Path) -> None:
    """Copy files referenced by absolute path into the project and rewrite the
    ext_resource path to a real res:// location."""
    try:
        text = tscn.read_text(encoding="utf-8")
    except OSError:
        return
    changed = False

    def _sub(m: "re.Match[str]") -> str:
        nonlocal changed
        raw = m.group(1).replace("\\", "/")
        src = Path(raw)
        if not src.exists():
            return m.group(0)  # leave it; nothing we can do
        target = dest / src.name
        if not target.exists():
            try:
                shutil.copy2(src, target)
            except OSError:
                return m.group(0)
        changed = True
        return f'path="res://{src.name}"'

    new = _ABS_REF.sub(_sub, text)
    if changed:
        tscn.write_text(new, encoding="utf-8")
