"""Assemble a throwaway Godot project to run an addon headlessly (TDD 24.3/24.7).

Laser Tag and Lux are Godot addons: their headless entry points are a runner /
driver script inside the addon, invoked with ``godot --headless --path <project>
-s res://<script> -- <args>``. The scene they operate on lives in a Level Factory
work dir, but Godot can only ``load()`` a ``res://`` path, so we stage a minimal
project that contains the addon(s) and the scene (plus its work-dir siblings) at
``res://``.

This is the seam, not a full resource-closure packer: it copies the scene and
the sibling files in its directory (the glbs / json the tscn references by
relative path in a Level Factory job). A deeper closure across res:// references
reuses the exporting/closure module and is the documented follow-up.
"""
from __future__ import annotations

import shutil
from pathlib import Path


def _project_godot(name: str, addon_plugins: list[str]) -> str:
    enabled = ", ".join(f'"res://addons/{p}/plugin.cfg"' for p in addon_plugins)
    return (
        "; Auto-generated by Level Factory staging — throwaway project.\n"
        "config_version=5\n\n"
        "[application]\n"
        f'config/name="{name}"\n'
        'config/features=PackedStringArray("4.7")\n\n'
        "[editor_plugins]\n"
        f"enabled=PackedStringArray({enabled})\n"
    )


def stage_godot_project(
    dest: Path, *, addon_dirs: list[Path], scene_src: Path,
    plugins: list[str], scene_res_name: str = "level.tscn",
) -> tuple[Path, str]:
    """Create a project at ``dest`` with the addons + the scene at res://.

    Returns (project_dir, res_scene_path) e.g. (.../staging/x, "res://level.tscn").
    """
    dest.mkdir(parents=True, exist_ok=True)
    (dest / "addons").mkdir(exist_ok=True)
    for addon in addon_dirs:
        if addon.exists():
            target = dest / "addons" / addon.name
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(addon, target)
    # Stage the scene + its work-dir siblings (relative-path deps) at res://.
    if scene_src.exists():
        shutil.copy2(scene_src, dest / scene_res_name)
        for sib in scene_src.parent.iterdir():
            if sib.is_file() and sib != scene_src:
                shutil.copy2(sib, dest / sib.name)
    (dest / "project.godot").write_text(
        _project_godot(dest.name, plugins), encoding="utf-8")
    return dest, f"res://{scene_res_name}"
